
export const rows = [
    { 
        id: 1, 
        name: 'mido',
        email: 'mido2000@gmail.com' , 
        age: '31', 
        phone:'012345678910', 
        address:'13 street hanfy bahlol, cairo, EgyPT',
        city:'cairo',
        zipCode: "020",
        registerId: 12345,
    },
    { 
        id: 2, 
        name: 'mido',
        email: 'mido2000@gmail.com' , 
        age: '31', 
        phone:'012345678910', 
        address:'13 street hanfy bahlol, cairo, EgyPT',
        city:'cairo',
        zipCode: "020",
        registerId: 12345,
    },
    { 
        id: 3, 
        name: 'mido',
        email: 'mido2000@gmail.com' , 
        age: '31', 
        phone:'012345678910', 
        address:'13 street hanfy bahlol, cairo, EgyPT',
        city:'cairo',
        zipCode: "020",
        registerId: 12345,
    },
    { 
        id: 4, 
        name: 'mido',
        email: 'mido2000@gmail.com' , 
        age: '31', 
        phone:'012345678910', 
        address:'13 street hanfy bahlol, cairo, EgyPT',
        city:'cairo',
        zipCode: "020",
        registerId: 12345,
    },
    { 
        id: 5, 
        name: 'mido',
        email: 'mido2000@gmail.com' , 
        age: '31', 
        phone:'012345678910', 
        address:'13 street hanfy bahlol, cairo, EgyPT',
        city:'cairo',
        zipCode: "020",
        registerId: 12345,
    },
    { 
        id: 6, 
        name: 'mido',
        email: 'mido2000@gmail.com' , 
        age: '31', 
        phone:'012345678910', 
        address:'13 street hanfy bahlol, cairo, EgyPT',
        city:'cairo',
        zipCode: "020",
        registerId: 12345,
    },
    { 
        id: 7, 
        name: 'mido',
        email: 'mido2000@gmail.com' , 
        age: '31', 
        phone:'012345678910', 
        address:'13 street hanfy bahlol, cairo, EgyPT',
        city:'cairo',
        zipCode: "020",
        registerId: 12345,
    },
  ];
export const columns = [
    { field: 'id', headerName: 'ID', flex: 1, headerAlign:"center" , align:"center"},
    { field: 'name', headerName: 'Name' , flex: 1, headerAlign:"center", align:"center"},
    { field: 'email', headerName: 'Email' , flex: 1, headerAlign:"center", align:"center"},
    { field: 'age', headerName: 'Age', flex: 1, headerAlign:"center" , align:"center"},
    { field: 'phone', headerName: 'Phone', flex: 1, headerAlign:"center" , align:"center"},
    { field: 'address', headerName: 'Address', flex: 1, headerAlign:"center" , align:"center"},
    { field: 'city', headerName: 'City', flex: 1, headerAlign:"center" , align:"center"},
    { field: 'zipCode', headerName: 'ZipCode', flex: 1, headerAlign:"center" , align:"center"},
  ];